import { z } from 'zod';
export const eventTypes = ['RUN_STARTED','RUN_RESET','RUN_FINISHED','RUN_FAILED','RUN_STOPPED','RUN_TIMING','SWARM_BASELINE','EMERGENT_CAPABILITY_FORMED','ATTACK_PATH_STARTED','ATTACK_PATH_BLOCKED','ATTACK_EXHAUSTED','AGENT_CREATED','AGENT_STARTED','AGENT_WAITING','AGENT_RESUMED','AGENT_MESSAGE','AGENT_FINISHED','AGENT_FAILED','AGENT_TERMINATED','TOOL_REQUEST','TOOL_ALLOWED','TOOL_DENIED','TOOL_RESULT','HTTP_REQUEST','HTTP_RESPONSE','ARTIFACT_DISCOVERED','CAPABILITY_GAINED','CAPABILITY_DELEGATED','CAPABILITY_REVOKED','TAINT_OBSERVED','PROVENANCE_PROPAGATED','POLICY_WARNING','POLICY_BLOCK','SENTINEL_PROPOSAL','SENTINEL_PROPOSAL_REJECTED','CONTAINMENT_APPLIED','AGENT_QUARANTINED','MESSAGE_BLOCKED','INCIDENT_REPORT_CREATED','CANARY_ACCESSED','CANARY_LEAK','CANARY_SAFE','WASMER_PROCESS_STARTED','WASMER_PROCESS_EXITED','TENKI_AUTH_OK','TENKI_AUTH_FAILED','TENKI_SANDBOX_CREATED','TENKI_PROVISION_STARTED','TENKI_PROVISION_READY','TENKI_HEALTH_FAILED','TENKI_RESET','TENKI_SANDBOX_DESTROYED','MODEL_REQUEST','MODEL_RESPONSE'] as const;
export const EventSchema = z.object({id:z.string().uuid(),sequence:z.number().int().positive(),runId:z.string(),timestamp:z.string().datetime(),agentId:z.string().optional(),eventType:z.enum(eventTypes),summary:z.string().max(2000),target:z.string().optional(),data:z.record(z.string(),z.unknown()).default({})});
export type RuntimeEvent = z.infer<typeof EventSchema>;
export type EventInput = Omit<RuntimeEvent,'id'|'sequence'|'timestamp'|'data'> & {data?:Record<string,unknown>};
export type Mode = 'OFF'|'MONITOR'|'ENFORCE';
export type Role = 'coordinator'|'recon'|'analyst'|'operator'|'sentinel';
export type Service = 'entry'|'internal'|'privileged'|'vault'|'collector';
export const SERVICES:Service[] = ['entry','internal','privileged','vault','collector'];
