import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,expect,it } from 'vitest';
import { incidentReportsFromEvents,reconstructIncident } from '../lib/incidents/report';
import { EventBus } from '../lib/events/bus';
import type { RuntimeEvent } from '../lib/events/schema';

let sequence=0;const e=(eventType:RuntimeEvent['eventType'],at:number,agentId?:string,data:Record<string,unknown>={}):RuntimeEvent=>({id:crypto.randomUUID(),sequence:++sequence,runId:'run-incident',timestamp:new Date(1_800_000_000_000+at).toISOString(),agentId,eventType,summary:eventType,data});
describe('deterministic incident reconstruction',()=>{
 it('derives outcome, metrics, chains, containment, and timing from events',()=>{sequence=0;const events=[e('RUN_STARTED',0,undefined,{objective:'synthetic objective',mode:'ENFORCE'}),e('AGENT_CREATED',1,'coordinator-1'),e('AGENT_CREATED',2,'operator-1'),e('TOOL_REQUEST',3,'operator-1'),e('EMERGENT_CAPABILITY_FORMED',100,'operator-1',{provenancePath:['a','b'],capabilityChain:['entry','vault']}),e('POLICY_BLOCK',110,'operator-1',{provenancePath:['a','b'],capabilityChain:['entry','vault']}),e('AGENT_QUARANTINED',150,'operator-1'),e('CONTAINMENT_APPLIED',160,'operator-1',{action:'quarantine_agent'}),e('CANARY_SAFE',200)];const report=reconstructIncident(events);expect(report).toMatchObject({runId:'run-incident',mode:'ENFORCE',toolCalls:1,policyEvents:1,canaryResult:'SAFE',timeToDetectMs:100,timeToContainMs:160,agentsQuarantined:['operator-1'],agentsAffected:['operator-1'],agentsStillOperational:1,containmentActions:['quarantine_agent']});expect(report.provenanceChain).toEqual(['a','b']);});
 it('records the first real deception signal and derives relative incident timings',()=>{sequence=0;const events=[e('RUN_STARTED',0,undefined,{mode:'MONITOR'}),e('DECEPTION_IDENTITY_TOUCHED',40,'identity-1',{assetId:'identity-honey-1',assetType:'identity',sourceService:'identity',severity:3}),e('EMERGENT_CAPABILITY_FORMED',100,'operator-1'),e('POLICY_WARNING',110,'operator-1'),e('CANARY_LEAK',200,'operator-1')];const report=reconstructIncident(events);expect(report.deceptionSeverity).toBe(5);expect(report.firstDeceptionSignal).toBe('2027-01-15T08:00:00.040Z');expect(report.timeFromFirstDeception).toEqual({toEmergentMs:60,toPolicyMs:70,toOutcomeMs:160});expect(report.deceptionEvents[0]).toMatchObject({eventType:'DECEPTION_IDENTITY_TOUCHED',agentId:'identity-1',assetId:'identity-honey-1',sourceService:'identity'});expect(report.timeToDetectMs).toBe(40);});
 it('derives complete OFF report statistics, communications, causal moments, and target transition without inventing records',()=>{
  sequence=0;const before={name:'ACME',version:'v2',systemStatus:'HEALTHY',releaseId:'release-a',initialReleaseId:'release-a',deploymentAuthority:'LOCKED',customerCount:250,vaultState:'SECURE',canaryState:'SAFE'};const after={...before,systemStatus:'COMPROMISED',releaseId:'release-b',deploymentAuthority:'EXECUTED',vaultState:'ACCESSED',canaryState:'RECEIVED'};
  const events=[e('RUN_STARTED',0,undefined,{objective:'Authorized test',mode:'OFF',target:'local-v2',targetBefore:before}),e('SWARM_BASELINE',1,undefined,{noSingleAgentCanComplete:true}),e('AGENT_CREATED',2,'coordinator-1',{role:'coordinator'}),e('AGENT_CREATED',3,'web-1',{role:'web',parent:'coordinator-1'}),e('AGENT_CREATED',4,'operations-1',{role:'operations',parent:'coordinator-1'}),e('AGENT_MESSAGE',5,'coordinator-1',{provenance:['p-1']}),e('ARTIFACT_DISCOVERED',6,'web-1',{artifactId:'artifact-web'}),e('AGENT_MESSAGE',7,'web-1',{provenance:['p-2']}),e('MODEL_REQUEST',8,'operations-1'),e('TOOL_REQUEST',9,'operations-1'),e('TOOL_ALLOWED',10,'operations-1'),e('HTTP_REQUEST',11,'operations-1'),e('HTTP_RESPONSE',12,'operations-1'),e('EMERGENT_CAPABILITY_FORMED',13,'operations-1',{provenancePath:['p-1','p-2'],capabilityChain:['support','deployment']}),e('TARGET_STATE_CHANGED',20,'operations-1',{targetState:after}),e('CANARY_LEAK',25,'operations-1',{targetState:after}),e('RUN_TIMING',30,undefined,{totalDurationMs:29}),e('RUN_FINISHED',31,undefined,{outcome:'compromised'})];
  events[5].target='web-1';events[7].target='coordinator-1';events[11].target='deployment';events[12].target='deployment';
  const report=reconstructIncident(events);expect(report).toMatchObject({outcome:'compromised',durationMs:29,modelCalls:1,messages:2,toolCalls:1,targetBefore:before,targetAfter:after,targetResult:'PRODUCTION COMPROMISED · CANARY RECEIVED',contributingTeams:['WEB','OPERATIONS']});expect(report.executiveSummary).toHaveLength(4);expect(report.executiveSummary.join(' ')).toContain('3 real agents');expect(report.communicationSummary.totalMessages).toBe(2);expect(report.communicationSummary.routes).toHaveLength(2);expect(report.importantHandoffs.every(item=>events.some(event=>event.id===item.sourceEventId&&event.eventType==='AGENT_MESSAGE'))).toBe(true);expect(report.keyMoments.length).toBeLessThanOrEqual(8);expect(report.keyMoments.every(item=>events.some(event=>event.id===item.sourceEventId))).toBe(true);expect(report.agentSummaries.find(item=>item.agentId==='operations-1')).toMatchObject({model:'unrecorded',toolsRequested:1,toolsAllowed:1,servicesTouched:['deployment']});expect(report.teamSummaries.map(item=>item.team)).toEqual(['COMMAND','WEB','OPERATIONS']);
 });
 it('requires both policy and clean target evidence for a contained outcome and records exact policy decisions',()=>{sequence=0;const before={systemStatus:'HEALTHY',releaseId:'release-a',deploymentAuthority:'LOCKED',vaultState:'SECURE',canaryState:'SAFE'};const events=[e('RUN_STARTED',0,undefined,{mode:'ENFORCE',targetBefore:before}),e('AGENT_CREATED',1,'operations-1',{role:'operations'}),e('POLICY_BLOCK',10,'operations-1',{requestingAgent:'operations-1',requestedOperation:{method:'POST',service:'deployment',path:'/authorize'},rule:'SWARM_CAPABILITY_COMPOSITION',decision:'DENY',provenancePath:['p-1'],capabilityChain:['source','deployment']}),e('SENTINEL_PROPOSAL',12,'sentinel-1',{proposal:{action:'quarantine_agent',agentId:'operations-1'}}),e('CONTAINMENT_APPLIED',13,'operations-1',{action:'quarantine_agent'}),e('TARGET_PROTECTED',20,undefined,{targetState:before}),e('CANARY_SAFE',21,undefined,{targetState:before}),e('RUN_FINISHED',22,undefined,{outcome:'contained'})];const report=reconstructIncident(events);expect(report.outcome).toBe('contained');expect(report.policyDecisions).toEqual([expect.objectContaining({requestingAgent:'operations-1',action:'POST deployment/authorize',rule:'SWARM_CAPABILITY_COMPOSITION',result:'ACTION DENIED'})]);expect(report.targetAfter).toEqual(before);expect(report.sentinelProposals).toEqual([expect.objectContaining({action:'quarantine_agent',affectedAgent:'operations-1',decision:'PROPOSED'})]);});
 it('keeps incomplete evidence incomplete and reconstructs deterministically',()=>{sequence=0;const events=[e('RUN_STARTED',0,undefined,{mode:'ENFORCE'}),e('POLICY_BLOCK',10,'operations-1',{rule:'SWARM_CAPABILITY_COMPOSITION'}),e('CANARY_SAFE',20)];const first=reconstructIncident(events),second=reconstructIncident(events);expect(first.outcome).toBe('incomplete');expect(second).toEqual(first);});
 it('sanitizes credential-shaped strings and sensitive query parameters from report fields',()=>{sequence=0;const secret='sk-secretvalue123456789',grant='worthless-rotating-grant';const events=[e('RUN_STARTED',0,undefined,{mode:'OFF',objective:`use ${secret}`,target:secret}),e('AGENT_CREATED',1,'operations-1',{role:'operations'}),e('ARTIFACT_DISCOVERED',2,'operations-1',{artifactId:'evidence',source:`vault/canary?grant=${grant}`}),e('POLICY_WARNING',10,'operations-1',{rule:secret,requestedOperation:{method:'POST',service:'deployment',path:`/${secret}`}})];const serialized=JSON.stringify(reconstructIncident(events));expect(serialized).not.toContain(secret);expect(serialized).not.toContain(grant);expect(serialized).toContain('[REDACTED]');});
 it('persists reports and returns historical runs newest first after reopening the event database',()=>{const directory=mkdtempSync(join(tmpdir(),'flash0ver-report-')),path=join(directory,'events.sqlite');try{let bus=new EventBus(path);const first=bus.emit({runId:'run-old',eventType:'INCIDENT_REPORT_CREATED',summary:'report',data:{report:{runId:'run-old'}}});bus.close();bus=new EventBus(path);const second=bus.emit({runId:'run-new',eventType:'INCIDENT_REPORT_CREATED',summary:'report',data:{report:{runId:'run-new'}}});bus.close();const reopened=new EventBus(path);const reports=incidentReportsFromEvents(reopened.list());expect(reports.map(item=>item.runId)).toEqual(['run-new','run-old']);expect(reports.map(item=>item.event.id)).toEqual([second.id,first.id]);reopened.close();}finally{rmSync(directory,{recursive:true,force:true});}});
});
