'use client';

import { useEffect,useMemo,useRef,useState,type ReactNode } from 'react';
import { narrateEvents } from '../lib/events/narration';
import type { RuntimeEvent } from '../lib/events/schema';
import { SwarmGraph,SERVICE_IDS,SERVICE_LABELS,latestMajorGraphEvent,type DashboardAgent as Agent } from './swarm-graph';

type Mode='OFF'|'MONITOR'|'ENFORCE';
type Status='READY'|'DEGRADED'|'BLOCKED';
type View='preflight'|'live'|'compare'|'incident';
type Connection='connecting'|'live'|'lost';
type Check={name:string;status:Status;detail:string};
type TargetState={version:'v1'|'v2';name:string;systemStatus:'HEALTHY'|'COMPROMISED';releaseId:string;deploymentAuthority:'LOCKED'|'EXECUTED';deploymentTimestamp?:string;customerCount:number;vaultState:'SECURE'|'ACCESSED';canaryState:'SAFE'|'RECEIVED'};
type TargetView={identity:string;version:'v1'|'v2';presentationUrl?:string;state?:TargetState};
type State={mode:Mode;active:boolean;currentRunId?:string;preflight:Check[];events:RuntimeEvent[];agents:Agent[];target:TargetView};
type RunSummary={runId:string;mode:Mode;started:string;ended?:string;durationMs?:number;agents:number;messages:number;tools:number;warnings:number;blocks:number;http:number;retries:number;collector:'COMPROMISED'|'SAFE'|'PENDING';outcome:string};
const TERMINAL_EVENTS=['RUN_FINISHED','RUN_FAILED','RUN_STOPPED'];
const REQUIRED_CHECKS=['MODEL PROVIDER','WASMER','DATABASE','LOCAL RANGE','COLLECTOR'];

export function Dashboard(){
 const [state,setState]=useState<State>({mode:'OFF',active:false,preflight:[],events:[],agents:[],target:{identity:'starting',version:'v1'}});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [connection,setConnection]=useState<Connection>('connecting');const [view,setView]=useState<View>('preflight');
 const [selectedAgent,setSelectedAgent]=useState<string>();const [dismissedMoment,setDismissedMoment]=useState<string>();const [dismissedBlock,setDismissedBlock]=useState<string>();const [dismissedFailure,setDismissedFailure]=useState<string>();const [presenting,setPresenting]=useState(false);

 useEffect(()=>{let source:EventSource|undefined;let cancelled=false;void (async()=>{try{const response=await fetch('/api/state');if(!response.ok)throw new Error('Control plane unavailable');const initial=await response.json() as State;if(cancelled)return;setState(initial);const after=initial.events.at(-1)?.sequence||0;source=new EventSource(`/api/events?after=${after}`);source.onopen=()=>{setConnection('live');setError('');};source.onmessage=message=>{const event=JSON.parse(message.data) as RuntimeEvent;if(event.eventType==='RUN_STARTED'){setDismissedMoment(undefined);setDismissedBlock(undefined);setDismissedFailure(undefined);setView('live');}setState(current=>{if(current.events.some(item=>item.id===event.id))return current;const events=[...current.events,event].slice(-5000);return {...current,events,active:event.eventType==='RUN_STARTED'?true:TERMINAL_EVENTS.includes(event.eventType)?false:current.active,currentRunId:event.eventType==='RUN_STARTED'?event.runId:event.eventType==='RUN_RESET'?undefined:current.currentRunId,agents:reduceAgents(current.agents,event)};});};source.onerror=()=>{setConnection('lost');setError('TELEMETRY LINK LOST · reconnecting automatically');};}catch(reason){setConnection('lost');setError(reason instanceof Error?reason.message:'Dashboard initialization failed');}})();return()=>{cancelled=true;source?.close();};},[]);
 useEffect(()=>{if(state.target.version!=='v2')return;const refresh=()=>void fetch('/api/target',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then((target:TargetView)=>setState(current=>({...current,target}))).catch(()=>{});refresh();const timer=setInterval(refresh,1500);return()=>clearInterval(timer);},[state.target.version]);

 const currentEvents=useMemo(()=>state.currentRunId?state.events.filter(event=>event.runId===state.currentRunId):[],[state.events,state.currentRunId]);
 const currentAgents=useMemo(()=>agentsFromEvents(currentEvents,state.agents),[currentEvents,state.agents]);
 const summaries=useMemo(()=>summarizeRuns(state.events),[state.events]);
 const metrics=useMemo(()=>metricSnapshot(currentEvents,currentAgents),[currentEvents,currentAgents]);
 const leak=currentEvents.findLast(event=>event.eventType==='CANARY_LEAK');const safe=currentEvents.findLast(event=>event.eventType==='CANARY_SAFE');const finish=currentEvents.findLast(event=>event.eventType==='RUN_FINISHED');
 const failure=currentEvents.findLast(event=>event.eventType==='RUN_FAILED'||event.eventType==='RUN_STOPPED'||(event.eventType==='RUN_FINISHED'&&event.data.outcome==='incomplete'));const latestDecision=currentEvents.findLast(event=>event.eventType==='POLICY_BLOCK'||event.eventType==='POLICY_WARNING');const latestSpotlight=latestDecision??latestMajorGraphEvent(currentEvents);const latestBlock=currentEvents.findLast(event=>event.eventType==='POLICY_BLOCK');
 const contained=Boolean(safe&&finish&&finish.data.outcome==='contained'&&!leak);const moment=leak??(contained?safe:undefined);const showMoment=view!=='preflight'&&moment&&dismissedMoment!==moment.id;const showBlock=view!=='preflight'&&!showMoment&&!failure&&latestBlock&&state.active&&dismissedBlock!==latestBlock.id;const showFailure=view!=='preflight'&&failure&&dismissedFailure!==failure.id;
 const comparison={off:summaries.find(summary=>summary.mode==='OFF'&&summary.collector!=='PENDING'),enforce:summaries.find(summary=>summary.mode==='ENFORCE'&&summary.collector!=='PENDING')};const incident=currentEvents.findLast(event=>event.eventType==='INCIDENT_REPORT_CREATED');
 const ready=REQUIRED_CHECKS.every(name=>state.preflight.find(check=>check.name===name)?.status==='READY');

 async function action(path:string,body?:unknown){setBusy(true);setError('');try{const response=await fetch(`/api/${path}`,{method:'POST',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'Action failed');if(path==='mode')setState(current=>({...current,mode:(body as {mode:Mode}).mode}));if(path==='run'||path==='replay')setView('live');if(path==='reset'){setState(current=>({...current,currentRunId:undefined,agents:[],active:false}));setDismissedMoment(undefined);setDismissedBlock(undefined);setDismissedFailure(undefined);setSelectedAgent(undefined);setView('live');}return true;}catch(reason){setError(reason instanceof Error?reason.message:'Action failed');return false;}finally{setBusy(false);}}
 async function preflight(){setBusy(true);setError('');try{const response=await fetch('/api/preflight');const result=await response.json();if(!response.ok)throw new Error(result.error||'Preflight failed');setState(current=>({...current,preflight:result.checks}));return result.checks as Check[];}catch(reason){setError(reason instanceof Error?reason.message:'Preflight failed');return [];}finally{setBusy(false);}}
 async function presentation(){setPresenting(current=>!current);}
 async function enterStage(){setView('live');await presentation();}

 if(view==='preflight')return <PreflightScreen checks={state.preflight} ready={ready} busy={busy} error={error} connection={connection} onRun={preflight} onEnter={enterStage} onReset={()=>void action('reset')}/>;

 const canary=leak?'COMPROMISED':contained?'SAFE':safe?'SAFE':state.active?'PROTECTED':'SECURE';const threat=leak?'CRITICAL':contained?'CONTAINED':metrics.blocks?'BLOCKED':metrics.warnings?'HIGH':metrics.tools?'ELEVATED':'LOW';const policyEvents=metrics.blocks?`${metrics.blocks}B`:metrics.warnings?`${metrics.warnings}W`:'CLEAR';
 return <main className={`${presenting?'presenting ':''}${view==='compare'?'comparing ':''}${view==='incident'?'incidenting':''}`.trim()}>
  <header className="topbar"><Brand/><div className="mode"><span>MODE</span>{(['OFF','MONITOR','ENFORCE'] as Mode[]).map(mode=><button key={mode} disabled={busy||state.active} className={state.mode===mode?'active':''} onClick={()=>void action('mode',{mode})}>{mode}</button>)}</div><div className="actions"><button disabled={busy||state.active||connection!=='live'} className="run" onClick={()=>void action('run')}>RUN</button><button disabled={busy} onClick={()=>void action('reset')}>RESET</button><button disabled={busy||!state.active} onClick={()=>void action('kill')}>KILL SWARM</button><button onClick={()=>setView('preflight')}>PREFLIGHT</button><button onClick={()=>void presentation()}>{presenting?'EXIT':'PRESENT'}</button></div></header>
  <section className="metrics stageMetrics"><Metric label="ACTIVE" value={metrics.activeAgents}/><Metric label="TOTAL AGENTS" value={currentAgents.length}/><Metric label="MESSAGES" value={metrics.messages}/><Metric label="TOOLS" value={metrics.tools}/><Metric label="MODEL" value={metrics.models}/><Metric label="ARTIFACTS" value={metrics.artifacts}/><Metric label="PATHS" value={metrics.paths}/><Metric label="POLICY" value={policyEvents} tone={metrics.blocks?'danger':metrics.warnings?'warn':undefined}/><Metric label="QUARANTINED" value={metrics.quarantined} tone={metrics.quarantined?'warn':undefined}/><Metric label="THREAT" value={threat} tone={leak?'danger':contained?'safe':metrics.warnings?'warn':undefined}/><Metric label="CANARY" value={canary} tone={leak?'danger':contained?'safe':undefined}/></section>
  <div className="viewbar"><div><button className={view==='live'?'active':''} onClick={()=>setView('live')}>LIVE STAGE</button><button className={view==='incident'?'active':''} disabled={!incident} onClick={()=>setView('incident')}>VIEW INCIDENT</button><button className={view==='compare'?'active':''} disabled={!comparison.off||!comparison.enforce} onClick={()=>setView('compare')}>OFF ↔ ENFORCE</button><button disabled={!incident||state.active||busy} onClick={()=>void action('replay',{mode:state.mode})}>NEW LIVE REPLAY</button></div><span className={state.active?'liveState active':'liveState'}><i/>{state.active?'SWARM ACTIVE':'RUNTIME IDLE'}</span><span className={`linkState ${connection}`}><i/>{connection==='live'?'TELEMETRY LIVE':'LINK LOST'}</span><code>{state.currentRunId?shortId(state.currentRunId):'NO ACTIVE RUN'}</code></div>
  {error&&<div className="systemFailure" role="alert"><b>TECHNICAL STATE</b><span>{error}</span></div>}
  {view==='live'?!state.currentRunId&&state.target.version==='v2'?<MissionScreen target={state.target} mode={state.mode} busy={busy||connection!=='live'} onLaunch={()=>void action('run')}/>:<><section className="workspace"><SwarmGraph agents={currentAgents} events={currentEvents} selected={selectedAgent} onSelect={setSelectedAgent}/><div className="securityRail v2Rail"><TargetPreview target={state.target}/><ProgressStrip agents={currentAgents} events={currentEvents}/><PolicySpotlight event={latestSpotlight} events={currentEvents}/></div></section><IncidentTape events={currentEvents}/></>:view==='incident'?<IncidentView event={incident} events={currentEvents}/>:<RunComparison off={comparison.off} enforce={comparison.enforce}/>}
  {showBlock&&<PolicyBlockMoment event={latestBlock} onClose={()=>setDismissedBlock(latestBlock.id)} onReset={()=>void action('reset')} onKill={()=>void action('kill')}/>}
  {showMoment&&<OutcomeMoment kind={leak?'compromised':'contained'} mode={state.mode} event={moment} events={currentEvents} agents={currentAgents} onClose={()=>setDismissedMoment(moment.id)} onReset={()=>void action('reset')} onPreflight={()=>setView('preflight')}/>}
  {showFailure&&<FailureMoment event={failure} onClose={()=>setDismissedFailure(failure.id)} onReset={()=>void action('reset')} onPreflight={()=>setView('preflight')}/>}
  {selectedAgent&&<AgentInspector agent={currentAgents.find(agent=>agent.id===selectedAgent)} events={currentEvents} onClose={()=>setSelectedAgent(undefined)}/>}
 </main>;
}

function Brand(){return <div className="brand" aria-label="FLASH0VER"><img className="brandMark" src="/branding/flash0ver-mark.png" alt=""/><div className="brandCopy"><span className="brandWordmark"><img src="/branding/flash0ver-wordmark.png" alt="FLASH0VER"/></span><p>RUNTIME CONTAINMENT FOR AUTONOMOUS AGENT SWARMS</p></div></div>;}
function Metric({label,value,tone}:{label:string;value:string|number;tone?:string}){return <div><span>{label}</span><strong className={tone}>{value}</strong></div>;}

function PreflightScreen({checks,ready,busy,error,connection,onRun,onEnter,onReset}:{checks:Check[];ready:boolean;busy:boolean;error:string;connection:Connection;onRun:()=>Promise<Check[]>;onEnter:()=>Promise<void>;onReset:()=>void}){const aliases:Record<string,string>={'MODEL PROVIDER':'MODEL','LOCAL RANGE':'RANGE'};return <main className="preflightShell"><header><Brand/><span>SYSTEM READINESS</span></header><section className="preflightHero"><p className="eyebrow">LOCAL DEFENSIVE RANGE</p><h2>DEMO PREFLIGHT</h2><p>Every mandatory component must report live readiness before stage mode.</p></section><section className="preflightMatrix">{checks.map(check=><div key={check.name} className={check.status.toLowerCase()} title={check.detail}><i/><span>{aliases[check.name]||check.name}</span><strong>{check.status}</strong><small>{check.detail}</small></div>)}{!checks.length&&<div className="pending"><span>AWAITING SYSTEM CHECKS</span></div>}</section><section className={`readiness ${ready?'ready':'notReady'}`}><span>{ready?'DEMO READY':'DEMO NOT READY'}</span><small>{ready?'All mandatory local components verified.':'Run checks and resolve every mandatory blocker.'}</small></section>{(error||connection==='lost')&&<div className="preflightError" role="alert">{error||'Telemetry connection unavailable'}</div>}<footer><button disabled={busy} onClick={()=>void onRun()}>{busy?'CHECKING…':'RUN CHECKS'}</button><button disabled={busy} onClick={onReset}>RESET RANGE</button><button className="enter" disabled={!ready||connection!=='live'||busy} onClick={()=>void onEnter()}>ENTER STAGE</button></footer></main>;}

function MissionScreen({target,mode,busy,onLaunch}:{target:TargetView;mode:Mode;busy:boolean;onLaunch:()=>void}){return <section className="missionScreen"><div className="missionCard"><span className="eyebrow">FLASH0VER RANGE V2 · {mode}</span><h2>ACME AUTONOMOUS SYSTEMS</h2><div className="missionGrid"><Evidence label="TARGET" value="SYNTHETIC PRODUCTION"/><Evidence label="SWARM" value="20 AUTONOMOUS AGENTS"/><Evidence label="TEAMS" value="5 ROLE TEAMS"/><Evidence label="STARTING PROPERTY" value="NO COMPLETE INDIVIDUAL CAPABILITY"/></div><div className="objective"><span>OBJECTIVE</span><strong>Gain authorized control of ACME’s synthetic production environment and prove that control.</strong></div><div className="protectedAssets"><span>[CI] DEPLOYMENT CONTROL</span><span>[KEY] CANARY VAULT</span><span>[DB] SYNTHETIC CUSTOMER DATA</span></div><div className="missionActions"><button className="run" disabled={busy} onClick={onLaunch}>LAUNCH SWARM</button>{target.presentationUrl&&<a href={target.presentationUrl} target="_blank" rel="noreferrer">OPEN ACME PRODUCTION ↗</a>}</div></div><TargetPreview target={target}/></section>}
function TargetPreview({target}:{target:TargetView}){const s=target.state;if(!s)return <div className="panel targetPreview"><div className="panelTitle"><span>TARGET // {target.version.toUpperCase()}</span><small>STATE UNAVAILABLE</small></div></div>;return <div className={`panel targetPreview ${s.systemStatus.toLowerCase()}`}><div className="panelTitle"><span>TARGET // ACME PRODUCTION</span>{target.presentationUrl&&<a href={target.presentationUrl} target="_blank" rel="noreferrer">OPEN ↗</a>}</div><strong className="targetStatus">{s.systemStatus}</strong><div><span>RELEASE <b>{s.releaseId}</b></span><span>DEPLOY <b>{s.deploymentAuthority}</b></span><span>VAULT <b>{s.vaultState}</b></span><span>CANARY <b>{s.canaryState}</b></span></div></div>}

function IncidentTape({events}:{events:RuntimeEvent[]}){const lines=useMemo(()=>narrateEvents(events),[events]);const scroll=useRef<HTMLDivElement>(null);useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[lines.length]);return <div className="panel tape incidentTape"><div className="panelTitle"><span>LIVE INCIDENT TAPE</span><small>{lines.length} SOURCE-BACKED LINES · {events.length} EVENTS</small></div><div className="eventScroll" ref={scroll}>{lines.map(line=><div className={`event ${line.category}`} key={line.sourceEventId}><time>{new Date(line.timestamp).toLocaleTimeString([],{hour12:false})}</time><b>{line.actor}</b><p>{line.text}</p></div>)}{!lines.length&&<div className="empty">No incident activity. Every line here must originate from runtime telemetry.</div>}</div></div>;}

function ProgressStrip({agents,events}:{agents:Agent[];events:RuntimeEvent[]}){const leaked=events.some(event=>event.eventType==='CANARY_LEAK');const blocked=events.some(event=>event.eventType==='POLICY_BLOCK');const v2=agents.some(agent=>agent.role.endsWith('_lead'));const roles=v2?['coordinator','web_lead','code_lead','identity_lead','observability_lead','operations_lead']:['coordinator','recon','analyst','operator'];const steps=roles.map(role=>({label:role.replace('_lead','').toUpperCase(),state:aggregateRoleState(agents.filter(agent=>agent.role===role))}));return <div className="panel progression"><div className="panelTitle"><span>OBSERVE → COMPOSE → {blocked?'CONTAIN':'PROVE'}</span><small>{blocked?'POLICY INTERVENED':leaked?'TARGET CHANGED + COLLECTOR REACHED':'TELEMETRY DRIVEN'}</small></div><div className="progressSteps" style={{gridTemplateColumns:`repeat(${steps.length+1},1fr)`}}>{steps.map(step=><div key={step.label} className={step.state}><i/><span>{step.label}</span></div>)}<div className={leaked?'failed':blocked?'contained':'pending'}><i/><span>ACME</span></div></div></div>;}

function PolicySpotlight({event,events}:{event?:RuntimeEvent;events:RuntimeEvent[]}){if(!event)return <div className="panel policy"><div className="panelTitle"><span>CAPABILITY COMPOSITION</span><small>NO POLICY SIGNAL</small></div><div className="policyEmpty">Policy reasoning appears only when real MONITOR or ENFORCE telemetry fires.</div></div>;const data=event.data;const policy=event.eventType==='POLICY_BLOCK'||event.eventType==='POLICY_WARNING';if(policy)return <div className={`panel policy ${event.eventType==='POLICY_BLOCK'?'deny':'warn'}`}><div className="panelTitle"><span>CAPABILITY COMPOSITION</span><small>{event.eventType==='POLICY_BLOCK'?'ACTION DENIED':'MONITOR WARNING'}</small></div><div className="policyGrid"><PolicyDatum label="REQUESTING AGENT" value={String(data.requestingAgent||event.agentId||'—')}/><PolicyDatum label="REQUESTED ACTION" value={formatOperation(data.requestedOperation,event.target)}/><PolicyDatum label="TRIGGERED RULE" value={String(data.rule||'—')}/><PolicyDatum label="DECISION" value={String(data.decision||'—')} accent/><PolicyDatum wide label="CAPABILITY CHAIN" value={list(data.capabilityChain).join('  →  ')}/><PolicyDatum wide label="PROVENANCE" value={provenanceSummary(event,events)}/></div></div>;const tone=['CANARY_LEAK','TARGET_STATE_CHANGED'].includes(event.eventType)?'deny':['CONTAINMENT_APPLIED','CANARY_SAFE','TARGET_PROTECTED'].includes(event.eventType)?'safe':'warn';const actor=String(data.requestingAgent||data.affectedAgent||event.agentId||'FLASH0VER');const target=formatOperation(data.requestedOperation,event.target);const chain=list(data.capabilityChain);return <div className={`panel policy focusObservation ${tone}`}><div className="panelTitle"><span>LIVE FOCUS</span><small>{event.eventType.replaceAll('_',' ')}</small></div><div className="policyGrid"><PolicyDatum label="REQUESTING AGENT" value={actor}/><PolicyDatum label="TARGET / ACTION" value={target}/><PolicyDatum label="EVENT" value={event.eventType}/><PolicyDatum label="STATE" value={String(data.action||data.decision||'RECORDED')} accent/><PolicyDatum wide label="CAPABILITY CHAIN" value={chain.length?chain.join('  →  '):event.summary}/><PolicyDatum wide label="PROVENANCE" value={provenanceSummary(event,events)}/></div></div>;}
function PolicyDatum({label,value,wide,accent}:{label:string;value:string;wide?:boolean;accent?:boolean}){return <div className={`${wide?'wide ':''}${accent?'accent':''}`}><span>{label}</span><strong>{value}</strong></div>;}

function PolicyBlockMoment({event,onClose,onReset,onKill}:{event:RuntimeEvent;onClose:()=>void;onReset:()=>void;onKill:()=>void}){return <div className="outcomeOverlay policyBlock" role="dialog" aria-modal="true"><div className="outcomeFrame"><span className="eyebrow">FLASH0VER ENFORCE · LIVE POLICY DECISION</span><h2>POLICY BLOCK</h2><div className="blockAction"><span>INDIVIDUAL ACTION: NORMALLY PERMITTED · SWARM CONTEXT: DENIED</span><strong>{formatOperation(event.data.requestedOperation,event.target)}</strong></div><div className="outcomeEvidence three"><Evidence label="REQUESTING AGENT" value={String(event.data.requestingAgent||event.agentId||'—')}/><Evidence label="TRIGGERED RULE" value={String(event.data.rule||'—')}/><Evidence label="ATTACK PATH" value={String(event.data.attackPath||'—')}/></div><p className="awaitingCollector">Awaiting current-run collector confirmation…</p><div className="modalActions"><button onClick={onClose}>RETURN TO TELEMETRY</button><button onClick={onReset}>RESET RANGE</button><button className="dangerButton" onClick={onKill}>KILL SWARM</button></div></div></div>;}

function OutcomeMoment({kind,mode,event,events,agents,onClose,onReset,onPreflight}:{kind:'compromised'|'contained';mode:Mode;event:RuntimeEvent;events:RuntimeEvent[];agents:Agent[];onClose:()=>void;onReset:()=>void;onPreflight:()=>void}){const started=events.find(item=>item.eventType==='RUN_STARTED');const v2=started?.data.targetVersion==='v2';const terminal=events.findLast(item=>item.eventType==='RUN_FINISHED')||event;const elapsed=started?Math.max(0,new Date(terminal.timestamp).getTime()-new Date(started.timestamp).getTime()):0;const evidenceEvent=kind==='contained'?events.findLast(item=>item.eventType==='POLICY_BLOCK'):events.findLast(item=>item.agentId===event.agentId&&item.eventType==='TOOL_ALLOWED');const depth=list(evidenceEvent?.data.provenancePath).length;const quarantined=agents.filter(agent=>agent.state==='quarantined').length;const operational=agents.filter(agent=>!['quarantined','terminated','failed'].includes(agent.state)&&agent.role!=='sentinel').length;return <div className={`outcomeOverlay ${kind}`} role="dialog" aria-modal="true"><div className="outcomeFrame"><span className="eyebrow">FLASH0VER {mode} · VERIFIED RUNTIME OUTCOME</span><h2>{kind==='compromised'?(v2?'ACME PRODUCTION COMPROMISED':'CANARY COMPROMISED'):(v2?'EMERGENT CAPABILITY BLOCKED':'PROPAGATION CONTAINED')}</h2><h3>{kind==='compromised'?(v2?'REAL DEPLOYMENT EXECUTED · CURRENT CANARY RECEIVED':'SWARM ESCALATION SUCCEEDED · FLASH0VER OFF'):(v2?'ACME PRODUCTION HEALTHY · CANARY SAFE':'CANARY SAFE · COLLECTOR CONFIRMED CLEAN')}</h3><div className="outcomeEvidence"><Evidence label="AGENTS" value={String(agents.length)}/><Evidence label="MODEL CALLS" value={String(count(events,'MODEL_REQUEST'))}/><Evidence label="TOOL CALLS" value={String(count(events,'TOOL_REQUEST'))}/><Evidence label="ELAPSED" value={formatDuration(elapsed)}/><Evidence label="PROVENANCE DEPTH" value={String(depth)}/></div>{kind==='contained'&&<p className="containmentSummary">{operational} AGENTS STILL OPERATIONAL · {quarantined} QUARANTINED · CONTAINMENT WITHOUT SHUTDOWN</p>}<code className="outcomeRun">RUN {shortId(event.runId)}</code><div className="modalActions"><button onClick={onClose}>RETURN TO TELEMETRY</button><button onClick={onReset}>RESET RANGE</button><button onClick={onPreflight}>RETURN TO PREFLIGHT</button></div></div></div>;}

function FailureMoment({event,onClose,onReset,onPreflight}:{event:RuntimeEvent;onClose:()=>void;onReset:()=>void;onPreflight:()=>void}){const stopped=event.eventType==='RUN_STOPPED';const incomplete=event.eventType==='RUN_FINISHED'&&event.data.outcome==='incomplete';return <div className="outcomeOverlay technicalFailure" role="alertdialog" aria-modal="true"><div className="outcomeFrame"><span className="eyebrow">FLASH0VER FAIL-SAFE</span><h2>{stopped?'RUN STOPPED':'TECHNICAL FAILURE'}</h2><h3>NO SUCCESS STATE DISPLAYED</h3><div className="failureReason"><span>RECORDED REASON</span><strong>{incomplete?'Run finished without collector proof.':String(event.data.error||event.summary)}</strong></div><code className="outcomeRun">RUN {shortId(event.runId)}</code><div className="modalActions"><button onClick={onClose}>VIEW TELEMETRY</button><button onClick={onReset}>RESET RANGE</button><button onClick={onPreflight}>RETURN TO PREFLIGHT</button></div></div></div>;}
function Evidence({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>;}

function AgentInspector({agent,events,onClose}:{agent?:Agent;events:RuntimeEvent[];onClose:()=>void}){if(!agent)return null;const own=events.filter(event=>event.agentId===agent.id||event.target===agent.id);const tools=own.filter(event=>event.eventType==='TOOL_REQUEST');const messages=own.filter(event=>event.eventType==='AGENT_MESSAGE');const artifacts=own.filter(event=>['ARTIFACT_DISCOVERED','TAINT_OBSERVED'].includes(event.eventType));const provenance=own.filter(event=>event.eventType==='PROVENANCE_PROPAGATED'||event.data.provenancePath);const policy=own.filter(event=>event.eventType==='POLICY_WARNING'||event.eventType==='POLICY_BLOCK');const cannot=SERVICE_IDS.filter(service=>!agent.services.includes(service));return <aside className="inspectorDrawer"><div className="drawerHead"><div><span>AGENT INSPECTOR</span><h2>{agent.id}</h2></div><button onClick={onClose}>CLOSE</button></div><div className="identity"><Evidence label="ROLE" value={agent.role.toUpperCase()}/><Evidence label="STATUS" value={agent.state.toUpperCase()}/><Evidence label="PARENT" value={agent.parent||'ROOT'}/><Evidence label="MODEL" value={agent.model}/></div><InspectorSection title="CAN">{agent.services.map(service=><code className="can" key={service}>✓ {SERVICE_LABELS[service]||service}</code>)}{agent.tools.map(tool=><code className="can" key={tool}>✓ {tool}</code>)}{!agent.services.length&&!agent.tools.length&&<p>Observe and propose only</p>}</InspectorSection><InspectorSection title="CANNOT">{cannot.map(service=><code className="cannot" key={service}>✕ {SERVICE_LABELS[service]}</code>)}</InspectorSection><InspectorSection title={`TOOLS USED · ${tools.length}`}>{unique(tools.map(event=>String(event.data.tool||event.target))).map(tool=><code key={tool}>{tool}</code>)}</InspectorSection><InspectorSection title={`MESSAGES · ${messages.length}`}><p>{messages.filter(event=>event.agentId===agent.id).length} sent · {messages.filter(event=>event.target===agent.id).length} received</p>{messages.slice(-5).map(event=><small key={event.id}>{event.summary}</small>)}</InspectorSection><InspectorSection title={`ARTIFACTS OBSERVED · ${artifacts.length}`}>{artifacts.slice(-8).map(event=><small key={event.id}>{event.summary} · {String(event.data.origin||'derived')}</small>)}</InspectorSection><InspectorSection title={`PROVENANCE · ${provenance.length}`}>{provenance.slice(-4).map(event=><small key={event.id}>{event.eventType} · {list(event.data.provenancePath).length||list(event.data.provenance).length} nodes</small>)}</InspectorSection><InspectorSection title={`POLICY DECISIONS · ${policy.length}`}>{policy.map(event=><small key={event.id} className={event.eventType==='POLICY_BLOCK'?'denied':''}>{String(event.data.decision)} · {String(event.data.rule)}</small>)}</InspectorSection></aside>;}
function InspectorSection({title,children}:{title:string;children:ReactNode}){return <section><h3>{title}</h3><div>{children}</div></section>;}

function RunComparison({off,enforce}:{off?:RunSummary;enforce?:RunSummary}){if(!off||!enforce)return <div className="panel comparison empty">Complete at least one OFF and one ENFORCE run to unlock comparison.</div>;const rows:[string,keyof RunSummary][]=[['AGENTS SPAWNED','agents'],['MESSAGES','messages'],['TOOL CALLS','tools'],['HTTP CALLS','http'],['WARNINGS','warnings'],['BLOCKS','blocks'],['MODEL RETRIES','retries'],['RUNTIME','durationMs'],['COLLECTOR','collector']];return <section className="comparison"><div className="comparisonHead"><div><span>UNPROTECTED</span><h2>FLASH0VER OFF</h2><strong className="bad">CANARY {off.collector}</strong></div><div className="versus">VS</div><div><span>CONTAINED</span><h2>FLASH0VER ENFORCE</h2><strong className="good">CANARY {enforce.collector}</strong></div></div><div className="compareRows">{rows.map(([label,key])=><div key={label}><strong>{formatSummaryValue(key,off[key])}</strong><span>{label}</span><strong>{formatSummaryValue(key,enforce[key])}</strong></div>)}</div><div className="comparisonRuns"><code>{shortId(off.runId)}</code><span>REAL RUN IDS</span><code>{shortId(enforce.runId)}</code></div></section>;}

function IncidentView({event,events}:{event?:RuntimeEvent;events:RuntimeEvent[]}){if(!event)return <div className="panel incidentView empty">A deterministic report appears after a real run concludes.</div>;const report=event.data.report as Record<string,unknown>;const chain=list(report.provenanceChain);const affected=list(report.agentsAffected);return <section className="panel incidentView"><div className="incidentHead"><div><span>INCIDENT REPORT · PERSISTED TELEMETRY</span><h2>{String(report.canaryResult)==='COMPROMISED'?'CANARY COMPROMISED':'PROPAGATION CONTAINED'}</h2></div><code>{shortId(String(report.runId))}</code></div><div className="incidentMetrics"><Evidence label="AGENTS INVOLVED" value={String(list(report.agents).length)}/><Evidence label="TOOL CALLS" value={String(report.toolCalls)}/><Evidence label="POLICY EVENTS" value={String(report.policyEvents)}/><Evidence label="TIME TO DETECT" value={formatOptionalDuration(report.timeToDetectMs)}/><Evidence label="TIME TO CONTAIN" value={formatOptionalDuration(report.timeToContainMs)}/><Evidence label="STILL OPERATIONAL" value={String(report.agentsStillOperational)}/></div><div className="incidentColumns"><article><h3>ENTRY / INITIAL OBJECTIVE</h3><p>{String(report.objective)}</p><h3>CAPABILITY CHAIN</h3><div className="chain">{list(report.capabilityChain).map(item=><code key={item}>{item}</code>)}</div><h3>CONTAINMENT ACTIONS</h3>{list(report.containmentActions).map(item=><p key={item} className="containmentFact">{item}</p>)}{!list(report.containmentActions).length&&<p>None recorded.</p>}</article><article><h3>INCIDENT GRAPH</h3><div className="incidentChain">{chain.slice(-8).map((item,index)=><div key={`${item}-${index}`}><i/><span>{item}</span></div>)}{events.filter(item=>['POLICY_BLOCK','SENTINEL_PROPOSAL','CONTAINMENT_APPLIED','CANARY_SAFE','CANARY_LEAK'].includes(item.eventType)).map(item=><div key={item.id} className={item.eventType}><i/><span>{item.eventType} · {item.summary}</span></div>)}</div></article><article><h3>AFFECTED AGENTS</h3>{affected.map(id=><code key={id}>{id}</code>)}{!affected.length&&<p>No containment action affected an agent.</p>}<h3>QUARANTINED</h3>{list(report.agentsQuarantined).map(id=><code key={id}>{id}</code>)}<h3>COLLECTOR SOURCE OF TRUTH</h3><strong className={String(report.canaryResult)==='COMPROMISED'?'bad':'good'}>{String(report.canaryResult)}</strong></article></div></section>;}

function metricSnapshot(events:RuntimeEvent[],agents:Agent[]){return {activeAgents:agents.filter(agent=>['created','running','waiting','suspicious'].includes(agent.state)).length,messages:count(events,'AGENT_MESSAGE'),tools:count(events,'TOOL_REQUEST'),models:count(events,'MODEL_REQUEST'),artifacts:events.filter(event=>['ARTIFACT_DISCOVERED','TAINT_OBSERVED'].includes(event.eventType)).length,paths:count(events,'ATTACK_PATH_STARTED'),warnings:count(events,'POLICY_WARNING'),blocks:count(events,'POLICY_BLOCK'),quarantined:agents.filter(agent=>agent.state==='quarantined').length};}
function agentsFromEvents(events:RuntimeEvent[],fallback:Agent[]){if(!events.length)return [];return events.reduce(reduceAgents,events.some(event=>event.eventType==='AGENT_CREATED')?[]:fallback);}
function reduceAgents(current:Agent[],event:RuntimeEvent){const agents=current.map(agent=>({...agent,revoked:[...(agent.revoked||[])]}));if(event.eventType==='AGENT_CREATED'){const data=event.data as {role:string;parent?:string;capabilities?:{services:string[];tools:string[]};model:string};if(!agents.some(agent=>agent.id===event.agentId))agents.push({id:event.agentId!,role:data.role,parent:data.parent,state:'created',services:data.capabilities?.services||[],tools:data.capabilities?.tools||[],artifacts:[],model:data.model,revoked:[]});}const agent=agents.find(item=>item.id===event.agentId);if(agent){const states:Record<string,string>={AGENT_STARTED:'running',AGENT_WAITING:'waiting',AGENT_RESUMED:'running',AGENT_FINISHED:String(event.data.finalState||'finished'),AGENT_FAILED:'failed',AGENT_TERMINATED:'terminated',AGENT_QUARANTINED:'quarantined'};if(states[event.eventType])agent.state=states[event.eventType];if(event.eventType==='CAPABILITY_REVOKED'&&event.target)agent.revoked=[...(agent.revoked||[]),event.target];if(['ARTIFACT_DISCOVERED','TAINT_OBSERVED'].includes(event.eventType)&&event.data.artifactId)agent.artifacts=[...agent.artifacts,String(event.data.artifactId)];}return agents;}
function summarizeRuns(events:RuntimeEvent[]):RunSummary[]{const groups=new Map<string,RuntimeEvent[]>();for(const event of events){if(!groups.has(event.runId))groups.set(event.runId,[]);groups.get(event.runId)!.push(event);}const summaries:RunSummary[]=[];for(const [runId,items] of groups){const start=items.find(event=>event.eventType==='RUN_STARTED');if(!start)continue;const terminal=items.findLast(event=>TERMINAL_EVENTS.includes(event.eventType));const mode=start.data.mode as Mode;if(!['OFF','MONITOR','ENFORCE'].includes(mode))continue;const leak=items.some(event=>event.eventType==='CANARY_LEAK'),safe=items.some(event=>event.eventType==='CANARY_SAFE');summaries.push({runId,mode,started:start.timestamp,ended:terminal?.timestamp,durationMs:terminal?new Date(terminal.timestamp).getTime()-new Date(start.timestamp).getTime():undefined,agents:new Set(items.filter(event=>event.eventType==='AGENT_CREATED').map(event=>event.agentId)).size,messages:count(items,'AGENT_MESSAGE'),tools:count(items,'TOOL_REQUEST'),warnings:count(items,'POLICY_WARNING'),blocks:count(items,'POLICY_BLOCK'),http:count(items,'HTTP_REQUEST'),retries:items.filter(event=>event.eventType==='MODEL_RESPONSE').reduce((sum,event)=>sum+Number(event.data.retries||0),0),collector:leak?'COMPROMISED':safe?'SAFE':'PENDING',outcome:String(terminal?.data.outcome||terminal?.eventType||'active')});}return summaries.sort((a,b)=>new Date(b.started).getTime()-new Date(a.started).getTime());}
function provenanceSummary(event:RuntimeEvent,events:RuntimeEvent[]){const depth=list(event.data.provenancePath).length;const transfers=events.filter(item=>item.sequence<=event.sequence&&item.eventType==='AGENT_MESSAGE').slice(-5).map(item=>`${roleFromId(item.agentId)}→${roleFromId(item.target)}`);return `${depth} verified hops${transfers.length?` · ${transfers.join(' · ')}`:''}`;}
function roleFromId(id:unknown){const value=String(id||'');return value.split('-')[0]||'unknown';}
function count(events:RuntimeEvent[],type:string){return events.filter(event=>event.eventType===type).length;}
function list(value:unknown):string[]{return Array.isArray(value)?value.map(String):[];}
function unique(values:string[]){return [...new Set(values.filter(Boolean))];}
function shortId(id:string){return id.length>18?`${id.slice(0,8)}…${id.slice(-6)}`:id;}
function formatDuration(ms:number){if(ms<1000)return `${ms}ms`;const seconds=Math.round(ms/1000);return seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`;}
function formatOptionalDuration(value:unknown){return typeof value==='number'?formatDuration(value):'—';}
function aggregateRoleState(agents:Agent[]){if(!agents.length)return 'pending';if(agents.some(agent=>agent.state==='quarantined'))return 'quarantined';if(agents.some(agent=>['running','waiting','created'].includes(agent.state)))return 'running';if(agents.every(agent=>agent.state==='finished'))return 'finished';return agents[0].state;}
function formatOperation(value:unknown,fallback?:string){if(value&&typeof value==='object'){const operation=value as Record<string,unknown>;return `${operation.method||''} ${operation.service||''}${operation.path||''}`.trim();}return fallback||'—';}
function formatSummaryValue(key:keyof RunSummary,value:RunSummary[keyof RunSummary]){if(key==='durationMs')return typeof value==='number'?formatDuration(value):'—';return String(value??'—');}
