'use client';

import { useMemo } from 'react';
import type { RuntimeEvent } from '../lib/events/schema';

export type DashboardAgent={id:string;role:string;state:string;parent?:string;services:string[];tools:string[];artifacts:string[];model:string;revoked?:string[]};
type EdgeKind='message'|'tool'|'http'|'artifact'|'delegation'|'composition'|'containment'|'blocked';
type GraphEdge={id:string;from:string;to:string;kind:EdgeKind;label:string;sequence:number;count:number};
type Point={x:number;y:number};
type VisualState='idle'|'active'|'thinking'|'working'|'sending'|'receiving'|'suspicious'|'blocked'|'quarantined'|'completed'|'terminated'|'failed';

export const SERVICE_IDS=['entry','internal','privileged','production','support','source','observability','identity','deployment','customer_db','vault','collector'] as const;
export const SERVICE_LABELS:Record<string,string>={entry:'[SUP] SUPPORT',internal:'[DOC] KNOWLEDGE',privileged:'[PRV] PRIVILEGED',production:'[WWW] PROD',support:'[SUP] SUPPORT',source:'[GIT] SOURCE',observability:'[LOG] OBSERVABILITY',identity:'[ID ] IDENTITY',deployment:'[CI ] DEPLOYMENT',customer_db:'[DB ] CUSTOMER DB',vault:'[KEY] VAULT',collector:'[OUT] COLLECTOR'};

const TEAMS=['web','code','identity','observability','operations'] as const;
const FOCUS_EVENTS=['AGENT_MESSAGE','PROVENANCE_PROPAGATED','CAPABILITY_DELEGATED','EMERGENT_CAPABILITY_FORMED','POLICY_WARNING','POLICY_BLOCK','ATTACK_PATH_BLOCKED','SENTINEL_PROPOSAL','CONTAINMENT_APPLIED','AGENT_QUARANTINED','AGENT_TERMINATED','TARGET_STATE_CHANGED','CANARY_ACCESSED','CANARY_LEAK','CANARY_SAFE'] as const;
const MAJOR_FOCUS_EVENTS=['EMERGENT_CAPABILITY_FORMED','POLICY_WARNING','POLICY_BLOCK','ATTACK_PATH_BLOCKED','SENTINEL_PROPOSAL','CONTAINMENT_APPLIED','AGENT_QUARANTINED','AGENT_TERMINATED','TARGET_STATE_CHANGED','CANARY_ACCESSED','CANARY_LEAK','CANARY_SAFE'];
const STATE_LABELS:Record<VisualState,string>={idle:'IDLE',active:'ACTIVE',thinking:'THINK',working:'WORK',sending:'SEND',receiving:'RECV',suspicious:'WATCH',blocked:'BLOCK',quarantined:'ISOLATED',completed:'DONE',terminated:'STOP',failed:'FAIL'};

export function SwarmGraph({agents,events,selected,onSelect}:{agents:DashboardAgent[];events:RuntimeEvent[];selected?:string;onSelect:(id:string)=>void}){
 const edges=useMemo(()=>graphEdges(events),[events]);
 const displayedEdges=useMemo(()=>compactEdges(edges),[edges]);
 const visibleServices=useMemo(()=>new Set(edges.flatMap(edge=>[edge.from,edge.to].filter(id=>isService(id)))),[edges]);
 const positions=useMemo(()=>layoutGraph(agents,[...visibleServices]),[agents,visibleServices]);
 const latestEdge=edges.at(-1);
 const latestSequence=events.at(-1)?.sequence??0;
 const latestFocusEvent=events.findLast(event=>FOCUS_EVENTS.includes(event.eventType as typeof FOCUS_EVENTS[number]));
 const latestMajorEvent=latestMajorGraphEvent(events);
 const focusEvent=latestMajorEvent&&latestSequence-latestMajorEvent.sequence<=24?latestMajorEvent:latestFocusEvent;
 const focusNodes=focusSet(focusEvent,agents);
 const focusActive=Boolean(focusEvent&&latestSequence-focusEvent.sequence<=8&&focusNodes.size);
 const newestAgent=events.findLast(event=>event.eventType==='AGENT_CREATED')?.agentId;
 const v2=agents.some(agent=>agent.role.endsWith('_lead'));
 return <div className="panel graph swarmMap"><div className="panelTitle"><span>ACME AUTONOMOUS SYSTEMS · SWARM COMMAND MAP</span><small>{agents.length?`${agents.length} REAL AGENTS · ${edges.length} EVENT EDGES · ${focusEvent?focusLabel(focusEvent):'OBSERVING'}`:'WAITING FOR RUN'}</small></div><div className={`graphCanvas ${focusActive?'focusMode':''}`}><svg viewBox="0 0 960 525" role="img" aria-label="Command map generated from live runtime telemetry"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z"/></marker><marker id="deny" markerWidth="12" markerHeight="12" refX="6" refY="6"><path d="M1,1 L11,11 M11,1 L1,11"/></marker><filter id="softGlow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
  <GraphArchitecture v2={v2} services={visibleServices.size}/>
  <g className="edgeLayer">{displayedEdges.map(edge=>{const from=positions.get(edge.from),to=positions.get(edge.to);if(!from||!to)return null;const active=edge.id===latestEdge?.id;const focused=focusNodes.has(edge.from)&&focusNodes.has(edge.to);return <g key={edge.id} className={`edge ${edge.kind} ${active?'active':''} ${focused?'focused':''} ${focusActive&&!focused&&!active?'dimmed':''}`}><path className="edgePath" d={edgePath(from,to,edge)} markerEnd={edge.kind==='blocked'?'url(#deny)':'url(#arrow)'}/><title>{edge.kind}: {edge.label}{edge.count>1?` · ${edge.count} real events`:''}</title></g>;})}</g>
  <g className="nodeLayer">{agents.map(agent=>{const point=positions.get(agent.id);if(!point)return null;const visual=agentVisualState(agent,events);const radius=nodeRadius(agent);const counters=agentCounters(agent,events);const focused=focusNodes.has(agent.id);const showCounters=focused||selected===agent.id||['thinking','working','sending','receiving'].includes(visual);return <g key={agent.id} transform={`translate(${point.x},${point.y})`} className={`agentNode team-${teamName(agent.role)} role-${roleClass(agent.role)} state-${visual} ${selected===agent.id?'selected':''} ${newestAgent===agent.id?'introduced':''} ${focused?'focused':''} ${focusActive&&!focused?'dimmed':''}`} role="button" tabIndex={0} onClick={()=>onSelect(agent.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')onSelect(agent.id);}}>
    {agent.role==='coordinator'&&<circle className="commandHalo" r={radius+12}/>}<circle className="stateRing" r={radius+6}/><circle className="nodeCore" r={radius}/><circle className="activityDot" cx={radius*.72} cy={-radius*.72} r="3.6"/>
    <text y="3" className="role">{roleCode(agent.role)}</text><g className="stateChip" transform={`translate(0 ${radius+9})`}><rect x="-18" y="-6" width="36" height="12" rx="6"/><text y="2.6">{STATE_LABELS[visual]}</text></g><text y={radius+27} className="nodeId">{agent.id.slice(-4).toUpperCase()}</text>
    {showCounters&&(counters.messages||counters.tools)>0&&<text y={-radius-11} className="microTelemetry">M{counters.messages} · T{counters.tools}</text>}<title>{agent.id} · {agent.role} · {STATE_LABELS[visual]} · {counters.messages} messages · {counters.tools} tools</title>
   </g>;})}
   {[...visibleServices].map(service=>{const point=positions.get(service);if(!point)return null;const state=serviceVisualState(service,events);const focused=focusNodes.has(service);return <g key={service} transform={`translate(${point.x},${point.y})`} className={`serviceNode service-${state} ${focused?'focused':''} ${focusActive&&!focused?'dimmed':''}`}><rect className="serviceFrame" x="-65" y="-16" width="130" height="32" rx="3"/><path className="serviceRail" d="M-57 9 H50"/><circle className="serviceIndicator" cx="55" cy="-8" r="3"/><text y="3">{SERVICE_LABELS[service]||service.toUpperCase()}</text><title>{SERVICE_LABELS[service]||service} · {state} · observed in real telemetry</title></g>;})}</g>
 </svg><div className="legend">{([['message','MESSAGE'],['tool','TOOL'],['http','HTTP'],['artifact','PROVENANCE'],['delegation','DELEGATION'],['composition','COMPOSITION'],['containment','CONTAINMENT'],['blocked','DENIED']] as [EdgeKind,string][]).map(([kind,label])=><span key={kind} className={kind}><i/>{label}</span>)}</div></div></div>;
}

function GraphArchitecture({v2,services}:{v2:boolean;services:number}){if(!v2)return <g className="architecture"><text className="columnLabel" x="24" y="18">COMMAND</text><text className="columnLabel" x="184" y="18">AGENT ROLES</text>{services>0&&<><rect className="infraRegion" x="760" y="20" width="190" height="485" rx="5"/><text className="columnLabel" x="778" y="38">TARGET INFRASTRUCTURE</text></>}</g>;return <g className="architecture"><rect className="commandRegion" x="10" y="20" width="105" height="485" rx="5"/><rect className="infraRegion" x="750" y="20" width="200" height="485" rx="5"/><text className="columnLabel" x="24" y="40">COMMAND</text><text className="columnLabel" x="168" y="18">TEAM LEADS</text><text className="columnLabel" x="372" y="18">AUTONOMOUS WORKERS</text><text className="columnLabel" x="775" y="40">TARGET INFRASTRUCTURE</text>{TEAMS.map((team,index)=>{const y=61+index*94;return <g className={`teamLane lane-${team}`} key={team}><rect x="132" y={y-35} width="588" height="70" rx="4"/><text x="143" y={y-23}>{team.toUpperCase()}</text></g>;})}</g>}

function graphEdges(events:RuntimeEvent[]):GraphEdge[]{const edges:GraphEdge[]=[];for(const event of events){if(event.eventType==='AGENT_MESSAGE'&&event.agentId&&event.target)edges.push(edge(event,event.agentId,event.target,'message','agent message'));if(event.eventType==='CAPABILITY_DELEGATED'&&event.agentId&&event.target)edges.push(edge(event,event.agentId,event.target,'delegation','capability delegation'));if(event.eventType==='EMERGENT_CAPABILITY_FORMED'){const chain=stringList(event.data.capabilityChain).filter(isService);const nodes=event.agentId?[event.agentId,...chain]:chain;nodes.slice(0,-1).forEach((from,index)=>edges.push(edge(event,from,nodes[index+1],'composition','emergent capability chain')));}if(event.eventType==='PROVENANCE_PROPAGATED'){const from=String(event.data.from||''),to=String(event.data.to||'');if(from&&to)edges.push(edge(event,from,to,'artifact','provenance transfer'));}if(event.eventType==='SENTINEL_PROPOSAL'&&event.agentId&&event.target)edges.push(edge(event,event.agentId,event.target,'containment','containment proposal'));if(event.eventType==='CONTAINMENT_APPLIED'&&event.agentId){const sentinel=String(event.data.proposedBy||'');if(sentinel)edges.push(edge(event,sentinel,event.agentId,'containment','validated containment'));}if(event.eventType==='TOOL_REQUEST'&&event.agentId){const service=(event.data.args as Record<string,unknown>|undefined)?.service;if(typeof service==='string'&&isService(service))edges.push(edge(event,event.agentId,service,'tool',String(event.data.tool||'tool request')));}if(event.eventType==='HTTP_REQUEST'&&event.agentId&&event.target)edges.push(edge(event,event.agentId,event.target,'http',event.summary));if(['ARTIFACT_DISCOVERED','TAINT_OBSERVED'].includes(event.eventType)&&event.agentId&&event.target)edges.push(edge(event,event.target,event.agentId,'artifact',event.summary));if(event.eventType==='POLICY_BLOCK'&&event.agentId&&event.target){const service=event.target.split('/')[0];if(isService(service))edges.push(edge(event,event.agentId,service,'blocked',event.summary));}}return edges;}
function edge(event:RuntimeEvent,from:string,to:string,kind:EdgeKind,label:string):GraphEdge{return {id:`${event.id}-${kind}-${from}-${to}`,from,to,kind,label,sequence:event.sequence,count:1};}
function compactEdges(edges:GraphEdge[]){const routes=new Map<string,GraphEdge>();for(const item of edges.slice(-180).reverse()){const key=`${item.from}|${item.to}|${item.kind}`;const existing=routes.get(key);if(existing)existing.count+=1;else routes.set(key,{...item});}return [...routes.values()].sort((a,b)=>a.sequence-b.sequence).slice(-55);}

function layoutGraph(agents:DashboardAgent[],services:string[]){const map=new Map<string,Point>();const v2=agents.some(agent=>agent.role.endsWith('_lead'));if(!v2){const roleX:Record<string,number>={coordinator:70,recon:225,analyst:410,operator:590,sentinel:705};const groups=new Map<string,DashboardAgent[]>();for(const agent of agents)groups.set(agent.role,[...(groups.get(agent.role)||[]),agent]);for(const [role,items] of groups)items.forEach((agent,index)=>map.set(agent.id,{x:roleX[role]||410,y:items.length===1?260:74+index*(372/Math.max(1,items.length-1))}));}else{for(const agent of agents)if(agent.role==='coordinator')map.set(agent.id,{x:63,y:261});else if(agent.role==='sentinel')map.set(agent.id,{x:697,y:261});TEAMS.forEach((team,index)=>{const y=61+index*94;const lead=agents.find(agent=>agent.role===`${team}_lead`);if(lead)map.set(lead.id,{x:210,y});const workers=agents.filter(agent=>agent.role===team);const slots=workerSlots(workers.length);workers.forEach((agent,worker)=>map.set(agent.id,{x:slots[worker]??450,y}));});}services.forEach((service,index)=>map.set(service,{x:850,y:61+index*(420/Math.max(1,services.length-1))}));return map;}
function workerSlots(count:number){if(count<=1)return[475];if(count===2)return[410,555];if(count===3)return[365,485,605];return Array.from({length:count},(_,index)=>350+index*(290/Math.max(1,count-1)));}

function agentVisualState(agent:DashboardAgent,events:RuntimeEvent[]):VisualState{if(agent.state==='quarantined')return'quarantined';if(agent.state==='terminated')return'terminated';if(agent.state==='failed')return'failed';const latestSequence=events.at(-1)?.sequence??0;const own=events.filter(event=>touchesAgent(event,agent.id));const latest=own.at(-1);if(latest&&latestSequence-latest.sequence<=8){if(['POLICY_BLOCK','TOOL_DENIED','MESSAGE_BLOCKED','ATTACK_PATH_BLOCKED'].includes(latest.eventType))return'blocked';if(['POLICY_WARNING','TAINT_OBSERVED'].includes(latest.eventType))return'suspicious';const modelRequest=own.findLast(event=>event.eventType==='MODEL_REQUEST');const modelResponse=own.findLast(event=>event.eventType==='MODEL_RESPONSE');if(modelRequest&&(!modelResponse||modelRequest.sequence>modelResponse.sequence))return'thinking';const toolRequest=own.findLast(event=>event.eventType==='TOOL_REQUEST'||event.eventType==='HTTP_REQUEST');const toolResult=own.findLast(event=>event.eventType==='TOOL_RESULT'||event.eventType==='HTTP_RESPONSE'||event.eventType==='TOOL_DENIED');if(toolRequest&&(!toolResult||toolRequest.sequence>toolResult.sequence))return'working';if(latest.eventType==='AGENT_MESSAGE')return latest.agentId===agent.id?'sending':'receiving';if(latest.eventType==='PROVENANCE_PROPAGATED')return String(latest.data.to||'')===agent.id?'receiving':'sending';if(latest.eventType==='ARTIFACT_DISCOVERED')return'receiving';}if(agent.state==='finished')return'completed';return agent.state==='running'?'active':'idle';}
function touchesAgent(event:RuntimeEvent,id:string){return event.agentId===id||event.target===id||String(event.data.from||'')===id||String(event.data.to||'')===id||String(event.data.requestingAgent||'')===id||String(event.data.affectedAgent||'')===id;}
function agentCounters(agent:DashboardAgent,events:RuntimeEvent[]){return{messages:events.filter(event=>event.eventType==='AGENT_MESSAGE'&&(event.agentId===agent.id||event.target===agent.id)).length,tools:events.filter(event=>event.eventType==='TOOL_REQUEST'&&event.agentId===agent.id).length};}

function focusSet(event:RuntimeEvent|undefined,agents:DashboardAgent[]){const set=new Set<string>();if(!event)return set;const candidates=[event.agentId,event.target,String(event.data.from||''),String(event.data.to||''),String(event.data.requestingAgent||''),String(event.data.affectedAgent||''),String(event.data.proposedBy||'')];for(const candidate of candidates){if(!candidate)continue;const service=candidate.split('/')[0];set.add(isService(service)?service:candidate);}const request=event.data.requestedOperation as Record<string,unknown>|undefined;if(typeof request?.service==='string'&&isService(request.service))set.add(request.service);for(const capability of stringList(event.data.capabilityChain))if(isService(capability))set.add(capability);if(event.eventType==='TARGET_STATE_CHANGED')set.add('production');if(event.eventType==='CANARY_ACCESSED')set.add('vault');if(event.eventType==='CANARY_LEAK')set.add('collector');if(event.eventType==='CANARY_SAFE')set.add('collector');for(const id of [...set]){let agent=agents.find(item=>item.id===id);while(agent?.parent){set.add(agent.parent);agent=agents.find(item=>item.id===agent?.parent);}}return set;}
function serviceVisualState(service:string,events:RuntimeEvent[]){if(service==='production'&&events.some(event=>event.eventType==='TARGET_STATE_CHANGED'))return'changed';if(service==='collector'&&events.some(event=>event.eventType==='CANARY_LEAK'))return'compromised';if(service==='vault'&&events.some(event=>event.eventType==='CANARY_ACCESSED'))return'accessed';const last=events.findLast(event=>event.target===service||(event.data.args as Record<string,unknown>|undefined)?.service===service);if(last?.eventType==='POLICY_BLOCK'||last?.eventType==='TOOL_DENIED')return'blocked';if(last&&['HTTP_REQUEST','TOOL_REQUEST'].includes(last.eventType))return'active';if(last?.eventType==='HTTP_RESPONSE')return Number(last.data.status)>=400?'warning':'healthy';return'idle';}

function edgePath(from:Point,to:Point,edge:GraphEdge){if(['http','tool','blocked','containment'].includes(edge.kind))return`M${from.x},${from.y} L${to.x},${to.y}`;const dx=to.x-from.x,dy=to.y-from.y,length=Math.max(1,Math.hypot(dx,dy));const direction=edge.sequence%2?1:-1;const bend=Math.min(24,length*.08)*direction;const cx=(from.x+to.x)/2-dy/length*bend,cy=(from.y+to.y)/2+dx/length*bend;return`M${from.x},${from.y} Q${cx},${cy} ${to.x},${to.y}`;}
function nodeRadius(agent:DashboardAgent){if(agent.role==='coordinator')return 30;if(agent.role==='sentinel')return 26;if(agent.role.endsWith('_lead'))return 24;return 19;}
function roleClass(role:string){if(role==='coordinator')return'coordinator';if(role==='sentinel')return'sentinel';return role.endsWith('_lead')?'lead':'worker';}
function teamName(role:string){return role.replace('_lead','');}
function roleCode(role:string){const codes:Record<string,string>={coordinator:'COO',sentinel:'SEN',web:'WEB',code:'COD',identity:'ID',observability:'OBS',operations:'OPS'};return role.endsWith('_lead')?'LEAD':codes[role]||role.slice(0,3).toUpperCase();}
function focusLabel(event:RuntimeEvent){const labels:Record<string,string>={AGENT_MESSAGE:'MESSAGE',PROVENANCE_PROPAGATED:'EVIDENCE',CAPABILITY_DELEGATED:'DELEGATION',EMERGENT_CAPABILITY_FORMED:'EMERGENT',POLICY_WARNING:'WARNING',POLICY_BLOCK:'DENIED',ATTACK_PATH_BLOCKED:'PATH BLOCKED',SENTINEL_PROPOSAL:'SENTINEL',CONTAINMENT_APPLIED:'CONTAINMENT',AGENT_QUARANTINED:'QUARANTINE',AGENT_TERMINATED:'TERMINATED',TARGET_STATE_CHANGED:'TARGET CHANGED',CANARY_ACCESSED:'VAULT ACCESSED',CANARY_LEAK:'COLLECTOR REACHED',CANARY_SAFE:'CANARY SAFE'};return labels[event.eventType]||event.eventType;}
function isService(value:string):value is typeof SERVICE_IDS[number]{return SERVICE_IDS.includes(value as typeof SERVICE_IDS[number]);}
function stringList(value:unknown):string[]{return Array.isArray(value)?value.map(String):[];}

export function latestMajorGraphEvent(events:RuntimeEvent[]){return events.findLast(event=>MAJOR_FOCUS_EVENTS.includes(event.eventType));}
